### ISSUE TITLE
client-error 403

### ISSUE THREAD

**Issue by davidkarlsen** [redhat-cop/volume-expander-operator#46]
operator has this error and can't extend the volumes.
We're on OCP 4.16
```
2024-09-27T10:50:59.646Z        ERROR   controllers.PersistentVolumeClaim       unable to query for used bytes  {"pvc": "ftm-hvp-dev/c-ftm-hvp-db2-meta", "query": "topk(1,kubelet_volume_stats_used_bytes{namespace=\"ftm-hvp-dev\",persistentvolumeclaim=\"c-ftm-hvp-db2-meta\"})", "error": "client_error: client error: 403"}
```

```
2025-01-02T23:57:52.918Z        ERROR   controllers.PersistentVolumeClaim       unable to poll metrics for      {"pvc": "ftm-hvp-sameep-dev/ftm-hvp-ace", "pvc": {"apiVersion": "v1", "kind": "PersistentVolumeClaim", "namespace": "ftm-hvp-sameep-dev", "name": "ftm-hvp-ace"}, "error": "client_error: client error: 403"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
2025-01-02T23:57:52.918Z        ERROR   controller-runtime.manager.controller.persistentvolumeclaim     Reconciler error        {"reconciler group": "", "reconciler kind": "PersistentVolumeClaim", "name": "ftm-hvp-ace", "namespace": "ftm-hvp-sameep-dev", "error": "client_error: client error: 403"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.2/pkg/internal/controller/controller.go:214
2025-01-02T23:57:52.918Z        DEBUG   controller-runtime.manager.events       Warning {"object": {"kind":"PersistentVolumeClaim","namespace":"ftm-hvp-sameep-dev","name":"ftm-hvp-ace","uid":"814bf632-6fa3-4546-9f3f-397155e84171","apiVersion":"v1","resourceVersion":"3896445431"}, "reason": "UnableToExtend", "message": "client_error: client error: 403"}
```

**Comment by davidkarlsen** [comment]
this should fix it:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volume-expander-operator-metrics-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: volume-expander-operator
```
